// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: IOTV2t

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PANELMODE = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PANELMODE, 120);
    lv_obj_set_height(ui_PANELMODE, 320);
    lv_obj_set_align(ui_PANELMODE, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_PANELMODE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PANELMODE, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PANELMODE, lv_color_hex(0x050F2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PANELMODE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PANELMODE, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PANELMODE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_Bar1, 30, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 45);
    lv_obj_set_height(ui_Bar1, 180);
    lv_obj_set_x(ui_Bar1, 38);
    lv_obj_set_y(ui_Bar1, 42);
    lv_obj_set_style_radius(ui_Bar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar1, lv_color_hex(0x2DA041), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_PANELREADSENSOR = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PANELREADSENSOR, 365);
    lv_obj_set_height(ui_PANELREADSENSOR, 130);
    lv_obj_set_x(ui_PANELREADSENSOR, 1);
    lv_obj_set_y(ui_PANELREADSENSOR, 0);
    lv_obj_set_align(ui_PANELREADSENSOR, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_PANELREADSENSOR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PANELREADSENSOR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PANELREADSENSOR, lv_color_hex(0x000C29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PANELREADSENSOR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TANKLAVE = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TANKLAVE, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TANKLAVE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TANKLAVE, 18);
    lv_obj_set_y(ui_TANKLAVE, 5);
    lv_label_set_text(ui_TANKLAVE, "TANK LEVEL");

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -180);
    lv_obj_set_y(ui_Label1, 85);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Mode");

    ui_STATEMODE = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_STATEMODE, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_STATEMODE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_STATEMODE, -180);
    lv_obj_set_y(ui_STATEMODE, 124);
    lv_obj_set_align(ui_STATEMODE, LV_ALIGN_CENTER);
    lv_label_set_text(ui_STATEMODE, "WAITING");

    ui_PHPANEL = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PHPANEL, 120);
    lv_obj_set_height(ui_PHPANEL, 60);
    lv_obj_set_x(ui_PHPANEL, -50);
    lv_obj_set_y(ui_PHPANEL, 40);
    lv_obj_set_align(ui_PHPANEL, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PHPANEL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PHPANEL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PHTSS = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PHTSS, 120);
    lv_obj_set_height(ui_PHTSS, 60);
    lv_obj_set_x(ui_PHTSS, 150);
    lv_obj_set_y(ui_PHTSS, 40);
    lv_obj_set_align(ui_PHTSS, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PHTSS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PHTSS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -160);
    lv_obj_set_y(ui_Label3, 15);
    lv_obj_set_align(ui_Label3, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label3, "SENSOR");

    ui_PANELCONTROL = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PANELCONTROL, 365);
    lv_obj_set_height(ui_PANELCONTROL, 100);
    lv_obj_set_x(ui_PANELCONTROL, 1);
    lv_obj_set_y(ui_PANELCONTROL, 125);
    lv_obj_set_align(ui_PANELCONTROL, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_PANELCONTROL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PANELCONTROL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PANELCONTROL, lv_color_hex(0x000C29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PANELCONTROL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 54);
    lv_obj_set_y(ui_Label4, -24);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "RELAY STATE");

    ui_PANELPUMPIN = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PANELPUMPIN, 80);
    lv_obj_set_height(ui_PANELPUMPIN, 40);
    lv_obj_set_x(ui_PANELPUMPIN, -60);
    lv_obj_set_y(ui_PANELPUMPIN, 24);
    lv_obj_set_align(ui_PANELPUMPIN, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PANELPUMPIN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PANELPUMPIN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PANELPUMPOUT = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PANELPUMPOUT, 80);
    lv_obj_set_height(ui_PANELPUMPOUT, 40);
    lv_obj_set_x(ui_PANELPUMPOUT, 60);
    lv_obj_set_y(ui_PANELPUMPOUT, 24);
    lv_obj_set_align(ui_PANELPUMPOUT, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PANELPUMPOUT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PANELPUMPOUT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PANELEC = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PANELEC, 80);
    lv_obj_set_height(ui_PANELEC, 40);
    lv_obj_set_x(ui_PANELEC, 180);
    lv_obj_set_y(ui_PANELEC, 24);
    lv_obj_set_align(ui_PANELEC, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PANELEC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PANELEC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -60);
    lv_obj_set_y(ui_Label5, -7);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "PUMP IN");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 60);
    lv_obj_set_y(ui_Label2, -7);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "PUMP OUT");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 180);
    lv_obj_set_y(ui_Label6, -7);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "EC");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PINS = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PINS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PINS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PINS, -60);
    lv_obj_set_y(ui_PINS, 24);
    lv_obj_set_align(ui_PINS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PINS, "READ");

    ui_POTS = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_POTS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_POTS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_POTS, 60);
    lv_obj_set_y(ui_POTS, 24);
    lv_obj_set_align(ui_POTS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_POTS, "READ");

    ui_ECS = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_ECS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ECS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ECS, 180);
    lv_obj_set_y(ui_ECS, 24);
    lv_obj_set_align(ui_ECS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ECS, "READ");

    ui_PANELSWITCMODE = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PANELSWITCMODE, 365);
    lv_obj_set_height(ui_PANELSWITCMODE, 100);
    lv_obj_set_x(ui_PANELSWITCMODE, 1);
    lv_obj_set_y(ui_PANELSWITCMODE, 2);
    lv_obj_set_align(ui_PANELSWITCMODE, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_PANELSWITCMODE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PANELSWITCMODE, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PANELSWITCMODE, lv_color_hex(0x000C29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PANELSWITCMODE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SWM = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_SWM, 50);
    lv_obj_set_height(ui_SWM, 25);
    lv_obj_set_x(ui_SWM, -70);
    lv_obj_set_y(ui_SWM, 112);
    lv_obj_set_align(ui_SWM, LV_ALIGN_CENTER);


    ui_Label7 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -70);
    lv_obj_set_y(ui_Label7, 82);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "MODE");

    ui_Label8 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -31);
    lv_obj_set_y(ui_Label8, 111);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "M");

    ui_Label9 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -106);
    lv_obj_set_y(ui_Label9, 112);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "A");

    ui_SWPIN = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_SWPIN, 50);
    lv_obj_set_height(ui_SWPIN, 25);
    lv_obj_set_x(ui_SWPIN, 35);
    lv_obj_set_y(ui_SWPIN, 112);
    lv_obj_set_align(ui_SWPIN, LV_ALIGN_CENTER);


    ui_Label10 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 35);
    lv_obj_set_y(ui_Label10, 82);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "PIN");

    ui_SWPOUT = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_SWPOUT, 50);
    lv_obj_set_height(ui_SWPOUT, 25);
    lv_obj_set_x(ui_SWPOUT, 110);
    lv_obj_set_y(ui_SWPOUT, 112);
    lv_obj_set_align(ui_SWPOUT, LV_ALIGN_CENTER);


    ui_Label11 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 110);
    lv_obj_set_y(ui_Label11, 82);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "POT");

    ui_SWPOUT1 = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_SWPOUT1, 50);
    lv_obj_set_height(ui_SWPOUT1, 25);
    lv_obj_set_x(ui_SWPOUT1, 185);
    lv_obj_set_y(ui_SWPOUT1, 112);
    lv_obj_set_align(ui_SWPOUT1, LV_ALIGN_CENTER);


    ui_Label12 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 185);
    lv_obj_set_y(ui_Label12, 82);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "EC");

    ui_Label13 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -97);
    lv_obj_set_y(ui_Label13, -108);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "pH");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 104);
    lv_obj_set_y(ui_Label14, -108);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "TSS");
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_phvllb = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_phvllb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_phvllb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_phvllb, -53);
    lv_obj_set_y(ui_phvllb, -91);
    lv_obj_set_align(ui_phvllb, LV_ALIGN_CENTER);
    lv_label_set_text(ui_phvllb, "READ");

    ui_tssvllb = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tssvllb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tssvllb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tssvllb, 151);
    lv_obj_set_y(ui_tssvllb, -91);
    lv_obj_set_align(ui_tssvllb, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tssvllb, "READ");

    ui_Label15 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 66);
    lv_obj_set_y(ui_Label15, 112);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "I");

    ui_Label16 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 2);
    lv_obj_set_y(ui_Label16, 112);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "0");

    ui_Label17 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 140);
    lv_obj_set_y(ui_Label17, 112);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "I");

    ui_Label18 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 77);
    lv_obj_set_y(ui_Label18, 112);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "0");

    ui_Label19 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 214);
    lv_obj_set_y(ui_Label19, 112);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "I");

    ui_Label20 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 154);
    lv_obj_set_y(ui_Label20, 112);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "0");

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 15);
    lv_obj_set_height(ui_Panel1, 27);
    lv_obj_set_x(ui_Panel1, -106);
    lv_obj_set_y(ui_Panel1, 145);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x000C29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 29);
    lv_obj_set_height(ui_Panel2, 27);
    lv_obj_set_x(ui_Panel2, -84);
    lv_obj_set_y(ui_Panel2, 145);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x000C29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel3, 38);
    lv_obj_set_height(ui_Panel3, 27);
    lv_obj_set_x(ui_Panel3, -23);
    lv_obj_set_y(ui_Panel3, 145);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x000C29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel4, 15);
    lv_obj_set_height(ui_Panel4, 27);
    lv_obj_set_x(ui_Panel4, -50);
    lv_obj_set_y(ui_Panel4, 145);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x000C29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, -84);
    lv_obj_set_y(ui_Label21, 145);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "ON");

    ui_Label22 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -50);
    lv_obj_set_y(ui_Label22, 145);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "0");

    ui_Label23 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, -106);
    lv_obj_set_y(ui_Label23, 145);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "I");

    ui_Label24 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, -22);
    lv_obj_set_y(ui_Label24, 145);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "OFF");

}
