// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: IOTV2t

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_PANELMODE;
lv_obj_t * ui_Bar1;
lv_obj_t * ui_PANELREADSENSOR;
lv_obj_t * ui_TANKLAVE;
lv_obj_t * ui_Label1;
lv_obj_t * ui_STATEMODE;
lv_obj_t * ui_PHPANEL;
lv_obj_t * ui_PHTSS;
lv_obj_t * ui_Label3;
lv_obj_t * ui_PANELCONTROL;
lv_obj_t * ui_Label4;
lv_obj_t * ui_PANELPUMPIN;
lv_obj_t * ui_PANELPUMPOUT;
lv_obj_t * ui_PANELEC;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label6;
lv_obj_t * ui_PINS;
lv_obj_t * ui_POTS;
lv_obj_t * ui_ECS;
lv_obj_t * ui_PANELSWITCMODE;
lv_obj_t * ui_SWM;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label9;
lv_obj_t * ui_SWPIN;
lv_obj_t * ui_Label10;
lv_obj_t * ui_SWPOUT;
lv_obj_t * ui_Label11;
lv_obj_t * ui_SWPOUT1;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Label14;
lv_obj_t * ui_phvllb;
lv_obj_t * ui_tssvllb;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Label24;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
