// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: IOTV2t

#ifndef _IOTV2T_UI_H
#define _IOTV2T_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_PANELMODE;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_PANELREADSENSOR;
extern lv_obj_t * ui_TANKLAVE;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_STATEMODE;
extern lv_obj_t * ui_PHPANEL;
extern lv_obj_t * ui_PHTSS;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_PANELCONTROL;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_PANELPUMPIN;
extern lv_obj_t * ui_PANELPUMPOUT;
extern lv_obj_t * ui_PANELEC;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_PINS;
extern lv_obj_t * ui_POTS;
extern lv_obj_t * ui_ECS;
extern lv_obj_t * ui_PANELSWITCMODE;
extern lv_obj_t * ui_SWM;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_SWPIN;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_SWPOUT;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_SWPOUT1;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_phvllb;
extern lv_obj_t * ui_tssvllb;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui____initial_actions0;





void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
